import { Amplify } from 'aws-amplify';
import { generateClient } from 'aws-amplify/data';

// Try to import amplify outputs (generated by deployment)
let amplifyConfig;
try {
  amplifyConfig = require('./amplify_outputs.json');
  console.log('Using deployed Amplify config');
} catch (error) {
  // Fallback config for local development
  amplifyConfig = {
    aws_project_region: 'us-east-1',
    aws_cognito_region: 'us-east-1',
    aws_user_pools_id: 'local-dev',
    aws_user_pools_web_client_id: 'local-dev',
    aws_cognito_identity_pool_id: 'local-dev',
    aws_appsync_graphqlEndpoint: 'http://localhost:20002/graphql',
    aws_appsync_region: 'us-east-1',
    aws_appsync_authenticationType: 'API_KEY',
    aws_appsync_apiKey: 'da2-fakeApiId123456'
  };
  console.log('Using local development config');
}

// Configure Amplify
Amplify.configure(amplifyConfig);

// Generate the data client
export const client = generateClient();

// Export config info
export const isLocal = !amplifyConfig.aws_appsync_graphqlEndpoint || amplifyConfig.aws_appsync_graphqlEndpoint.includes('localhost');

export default amplifyConfig;